version: "3"
services:
  redis:
    container_name: redis
    image: redis:latest
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - 6379:6379
    volumes:
      - type: bind
        source: ./data
        target: /data
      - ./redis.conf:/etc/redis/redis.conf
